service: serverless-aws-node-rest-api-mongodb

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs6.10
  vpc:
    securityGroupIds:
     - "sg-db38a1xx"
    subnetIds:
     - "subnet-44e59exx"

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
    vpc:
      securityGroupIds:
        - "sg-db38a1xx"
      subnetIds:
        - "subnet-44e59exx"

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
plugins:
  - serverless-offline